### ISSUE TITLE
Pie issue

### ISSUE THREAD

**Issue by jiangws88** [wezmag/SereneDashboardSample#2]
Hi Wezmag, 

I have tried your dashboard sample, but pie had issue as below:

![image](https://github.com/wezmag/SereneDashboardExample/assets/140736331/e1147db5-3a19-4515-88c2-3d9a8b0e365e)

jquery-3.5.1.js?v=2023082608:4055  Uncaught Error: No lookup with key "Northwind.Category" is registered. Please make sure you have a [LookupScript("Northwind.Category")] attribute in server side code on top of a row / custom lookup and  its key is exactly the same.
    at loadError (scriptdata.ts:153:15)
    at Object.ensure (scriptdata.ts:165:13)
    at getLookup (scriptdata.ts:220:23)
    at LookupEditorBase.getLookup (lookupeditor.ts:62:16)
    at LookupEditorBase.updateItems (lookupeditor.ts:96:28)
    at LookupEditor.LookupEditorBase [as constructor] (lookupeditor.ts:17:18)
    at new LookupEditor (lookupeditor.ts:145:15)
    at yi.initCategorySelect (SalesByCategoryPieWidget.ts:30:31)
    at new SalesByCategoryPieWidget (SalesByCategoryPieWidget.ts:17:14)
    at new DashboardPage (DashboardPage.ts:21:9)

Please advise.

**Comment by jiangws88** [comment]
solved it by myself, thank you.
